### ISSUE TITLE
Run a command not a program? 

### ISSUE THREAD

**Issue by blazeb5** [thagrol/Guides#22]
I have read the entire pdf, and associated forums where people have specific problems. All I want is for a specific gpio pin (17) to start in mode "a3" on boot. I can get the pin when set as an output to not trigger on boot, as it is "on" when booted and I have a script that sets it to not on on boot. However, simply adding "@reboot raspi-gpio set 17 a3" does not actually set the pin to a3 mode unless I run that command inthe command window as raspi-gpio set 17 a3...

Is there a simple way to just write in the command into the boot config.txt file i am running?

thank you for your time and efforts!

**Comment by thagrol** [comment]
Closing because:

1. This is off topic. It's not about the guide itself but rather about a specific use case.
2. I don't do private support/consultancy.
3. You don't appear to have tried even the most basic of troubleshooting steps from section 7 (specifically 7.1.3)
4. I don't have an answer for you. I've never used raspi-gpio. (Note: raspi-gpio **is** a program not a command).

For you config.txt question, all I can do is refer you to the [official documentation](https://www.raspberrypi.com/documentation/computers/config_txt.html#what-is-config-txt).

If my troubleshooting advice and the official documentation doesn't help I suggest opening a new topic on the Raspberry Pi Forums. Please don't add a new post in the thread about the guide as that will only result in my asking the moderators to move or delete it.

**Comment by blazeb5** [comment]
Sorry to be a bother. I was able to figure it out.

I thought my post was the way to go but I see that was an error. I think
what I learned would be helpful but no idea where it goes or who would
care.

**Comment by thagrol** [comment]
You weren't being a bother.

I'm hoping to avoid this repo from becoming flooded with issues and support requets like yours that are only indirectly related to the guides and scripts contained here.

And, like I said, I genuinely don't have an answer for you.

**Comment by blazeb5** [comment]
I'm a noob and explaining things poorly. This is just between you and me
via email, correct? If not, please just delete this from online.

Basically I was having issues with running not a script or program, but a
simple command line. Ultimately the solution was in sudo chron -e
modification. Admittedly it is in your pdf but it took me experimenting
past where I was comfortable after I posted to you online.

Adding @reboot <cmd> to the chron -e will run the command when the system
boots. Again, I just wasn't sure if this was helpful to new folks that are
thick skulled like me. (I don't know how to write a script with an
executable command yet.)

OK,  that's all from me. Thanks for your hard work on this.
 73s and cheers,
Brandon
